### ISSUE TITLE
Variable highlighting

### ISSUE THREAD

**Issue by jonathantneal** [hudochenkov/Syntax-highlighting-for-PostCSS#1]
This is the finest syntax highlighter I’ve used with Sublime Text. Could it parse valid CSS variables? Would it be in scope to parse Sassy variables?

![variable highlighting proposal](https://cloud.githubusercontent.com/assets/188426/10920783/117fdd74-8240-11e5-91c4-47b9a8b1e843.png)

The subtle highlighting of `var` and `--hello` make a world of readability difference.

**Comment by hudochenkov** [comment]
> This is the finest syntax highlighter I’ve used with Sublime Text.

Thanks to @P233 for making so flexible Sass highlighting :) It's time for me to learn how to make syntax highlighting now :)

What is your proposal for this highlighting? Maybe somewhere in your code you see something that looks like you want to look CSS variables? Or this screenshot is your proposal?

There is maybe not an issue with syntax highlighter but with color schemes. Not every color scheme support this highlighting [according to original readme](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/blob/master/README.original-sass.md#color-scheme).

Monokai Bright:

![screen shot 2015-11-04 at 00 09 53](https://cloud.githubusercontent.com/assets/654597/10921979/afc70360-8289-11e5-83a4-9df697857bbc.png)

Espresso Soda (i'm using it):

![screen shot 2015-11-04 at 00 09 29](https://cloud.githubusercontent.com/assets/654597/10921995/cec681dc-8289-11e5-8ec6-81893047d45a.png)

Tomorrow (bright one; featured in original readme as supported):

![screen shot 2015-11-04 at 00 13 36](https://cloud.githubusercontent.com/assets/654597/10922021/f8244352-8289-11e5-8496-5cc1f65eab25.png)

**Comment by hudochenkov** [comment]
I've also added highlighting for variables in `:root`:

| Before | After |
| --- | --- |
| ![screen shot 2015-11-04 at 10 27 44](https://cloud.githubusercontent.com/assets/654597/10932327/f17fa83c-82e0-11e5-8910-d4df660922d1.png) | ![screen shot 2015-11-04 at 10 27 28](https://cloud.githubusercontent.com/assets/654597/10932333/fad24f2a-82e0-11e5-9aa2-57000f23bacc.png) |

**Comment by hudochenkov** [comment]
Released 1.1.0. Hope [Package Control update](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20PostCSS) it soon.
