### ISSUE TITLE
CSS autocompletion does not work

### ISSUE THREAD

**Issue by jeremychone** [hudochenkov/Syntax-highlighting-for-PostCSS#10]
Somehow, on my ".pcss" files that are edited with PostCSS, I do not get any auto complete. 

I created a `../User/PostCSS.sublime-settings' file with: 

``` json
{
  "auto_complete": true
}
```

but still no luck.

Love this plugin, but I really miss autocompletion, even the most basic ones.

**Comment by movie4** [comment]
+1

**Comment by hudochenkov** [comment]
I've added basic completions. Update `2.1.0` will be available in a hour. I recommend to use [Emmet](https://github.com/sergeche/emmet-sublime) or [Hayaku](https://github.com/hayaku/hayaku) for better completions.
