### ISSUE TITLE
Add SugarSS

### ISSUE THREAD

**Issue by Dezeter** [hudochenkov/Syntax-highlighting-for-PostCSS#11]
You are going to add [SugarSS](https://github.com/postcss/sugarss)?

**Comment by hudochenkov** [comment]
I have no plans, but PR is welcome. It can be based on [Sass syntax highlighting](https://github.com/P233/Syntax-highlighting-for-Sass), I think.

**Comment by mg901** [comment]
Also Atom's PostCSS plugin support SugarSS too.

**Comment by ai** [comment]
@hudochenkov Sublime plugin development is hard, maybe you could create a syntax file just based on Sass syntax?

**Comment by hudochenkov** [comment]
@ai I can say for sure that I'm not going to add support by myself, because I don't use SugarSS. But PR is always welcome.

**Comment by maxinspace** [comment]
@ai @hudochenkov could you please check the solution?
https://github.com/maximlarionov/Syntax-highlighting-for-SugarSS

That actually a pure copy from Atom SugarSS plugin.

**Comment by ai** [comment]
@maximlarionov great! Should we merge this two plugins or you want to have it separated?

**Comment by maxinspace** [comment]
@ai well, let's merge, I don't actually mind :) Should I open pull-request?

**Comment by hudochenkov** [comment]
Have just released new version with @maximlarionov's help. It will be available in an hour in Package Control.
