### ISSUE TITLE
Remove fork badge

### ISSUE THREAD

**Issue by ai** [hudochenkov/Syntax-highlighting-for-PostCSS#14]
Fork badge is bad, because your repo doesn’t showed as separated project.

You can send a email to GitHub team and they will remove `fork` status.

**Comment by hudochenkov** [comment]
Where doesn't it showed as a separate project?

**Comment by ai** [comment]
It doesn’t show in search: https://github.com/search?utf8=%E2%9C%93&q=Syntax-highlighting-for-PostCSS&type=Repositories&ref=searchresults

Also contributions to forks are not counted on users profiles.

**Comment by ai** [comment]
`postcss-cli` disconnected fork too: https://github.com/postcss/postcss-cli/issues/41

**Comment by hudochenkov** [comment]
Didn't know this. Thank you.

I've contacted Github already.

**Comment by hudochenkov** [comment]
They did it! Now it's not a fork anymore :)
