### ISSUE TITLE
Doesn't support custom properties set @apply syntax

### ISSUE THREAD

**Issue by bessey** [hudochenkov/Syntax-highlighting-for-PostCSS#16]
![image](https://cloud.githubusercontent.com/assets/708200/26427287/f2398b98-4090-11e7-99d0-d8b0ce069c87.png)

[CSS next feature for reference](http://cssnext.io/features/#custom-properties-set-apply)

**Comment by bessey** [comment]
Couldn't screenshot it, but hovering over `@apply` reveals the error
`[postcss] } expected`
and hovering over the class names reveals
`[postcss] Do not use empty rulesets <element class="contact-details">`

**Comment by hudochenkov** [comment]
Are you sure you reporting to the correct repository? It looks like it's not a Sublime Text. And syntax highlighting can't show any errors or messages in Sublime Text.

**Comment by hudochenkov** [comment]
BTW, `@apply` is not an official spec. And it's [abandoned](http://www.xanthir.com/b4o00) by its author.

**Comment by bessey** [comment]
Apologies, I clicked through from a link in the VS Code adaptation. Ignore me!

Thanks for the link, very informative. All these not so official specs have got me a bit disenchanted over CSS Next. Far from being like the Babel stage-X presets, it seems more like a collection of features that may or may not ever end up in CSS...
