### ISSUE TITLE
attr/format/url with string concatenation

### ISSUE THREAD

**Issue by tenub** [hudochenkov/Syntax-highlighting-for-PostCSS#18]
Using `attr`, `format`, or `url` with string concatenation ruins proceeding syntax highlighting. I believe a fix would be as simple as changing:

`<string>(?&lt;=url\(|format\(|attr\().+(?=\))</string>`

to

`<string>(?&lt;=url\(|format\(|attr\().+?(?=\))</string>`

in [Syntaxes/PostCSS.tmLanguage](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/blob/master/Syntaxes/PostCSS.tmLanguage#L398)

Sample of issue:
![before](https://user-images.githubusercontent.com/1896007/26849852-a0f83890-4ad3-11e7-8ab6-ccb2e80bfd6b.png)

Sample of fix:
![after](https://user-images.githubusercontent.com/1896007/26849860-a68d4f7a-4ad3-11e7-9794-eebe966ca447.png)

**Comment by hudochenkov** [comment]
Thank you very much for fixing this problem! Update should be available in an hour or two in Package Control.

P. S. Like your Quake logo on avatar :)
