### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ai** [hudochenkov/Syntax-highlighting-for-PostCSS#19]
@hudochenkov hi, thanks for syntax highlighter. It becomes extremely useful to add PostCSS support to GitHub.

But they need a `LICENSE` file in the project root.

They need some license from [this list](https://github.com/github/linguist/blob/257425141d4e2a5232786bf0b13c901ada075f93/vendor/licenses/config.yml#L2-L11). I recommend MIT.

**Comment by hudochenkov** [comment]
@ai thank you for pointing out! Just added. Hope your PR will be approved :)
