### ISSUE TITLE
Cannot set extension to syntax

### ISSUE THREAD

**Issue by elliottmangham** [hudochenkov/Syntax-highlighting-for-PostCSS#21]
Hello,

I need to be able to set all `.css` files to use the PostCSS syntax, however, it is not listed as an option.

<img width="933" alt="Screenshot 2020-01-29 at 19 48 25" src="https://user-images.githubusercontent.com/12933804/73391769-7c0bcb80-42d0-11ea-8326-f583003c3403.png">

Please can you advise or fix?

Thank you!

**Comment by hudochenkov** [comment]
In the last list go to Syntax Highlighting for PostCSS.

**Comment by elliottmangham** [comment]
How on Earth did I miss that!? Thank you.
