### ISSUE TITLE
Using Midas

### ISSUE THREAD

**Issue by ai** [hudochenkov/Syntax-highlighting-for-PostCSS#3]
Midas is a awesome highlighter for PostCSS
https://github.com/ben-eb/midas

**Comment by hudochenkov** [comment]
Thank you for mention. I'm aware of it and will be happy of using it, but it won't work for this project. Sublime Text syntax highlighting based on plist files (xml-like) and using RegEx for parsing :( There is no way to use something different.

**Comment by tommillard** [comment]
Much needed package, thanks!

There seems to be a slight bug when a variable name follows a space and an opening parenthesis.

This doesn't highlight correctly: 

max-width: calc($desktopImageSize * ($desktopColumns - 1));

This does: 

max-width: calc($desktopImageSize *($desktopColumns - 1));
