### ISSUE TITLE
Coloring bug when variable name following space and opening parenthesis

### ISSUE THREAD

**Issue by tommillard** [hudochenkov/Syntax-highlighting-for-PostCSS#4]
There seems to be a slight bug when a variable name follows a space and an opening parenthesis.

This doesn't highlight correctly:

max-width: calc($desktopImageSize \* ($desktopColumns - 1));

This does:

max-width: calc($desktopImageSize *($desktopColumns - 1));

**Comment by hudochenkov** [comment]
Some color scheme differences in here:

Monokai Bright:
![image](https://cloud.githubusercontent.com/assets/654597/11090419/c4e5d218-8882-11e5-9d2e-4a7073bc2372.png)

Espresso Soda:
![image](https://cloud.githubusercontent.com/assets/654597/11090425/d236cba2-8882-11e5-9eb7-393cba0dcf84.png)

I'm sorry I can't fix this quick. Probably with this syntax highlighting modified color schemes should come additionally.

**Comment by hudochenkov** [comment]
Fixed in `1.1.1`. Soon will be updated in Package Control.
