### ISSUE TITLE
Not connected to auto-complete

### ISSUE THREAD

**Issue by JamesJosephFinn** [hudochenkov/Syntax-highlighting-for-PostCSS#7]
Auto-complete (tab completion) is not functional.

**Comment by hudochenkov** [comment]
I've never used it, and even don't know how to enable it. I just using [Emmet](https://github.com/sergeche/emmet-sublime) for all CSS related completions.

PR is welcome :)

**Comment by JamesJosephFinn** [comment]
It is core functionality out of the box with Sublime.

I can't take on any new stuff right now, so you can close this issue, if you want, or leave it up for someone else to take on.

And, thank you for making the tool!

**Comment by hudochenkov** [comment]
I strongly recommend to invest some time to learn Emmet, because it's huge time saver for CSS/HTML development. Emmet is Top 2 package for Sublime Text https://packagecontrol.io/browse/popular :)

**Comment by JamesJosephFinn** [comment]
I'm right there with you. I use (and love) Emmet for markup, but still haven't learned the abbreviations for styles, as of yet. I guess I should step my game up. :)

**Comment by JamesJosephFinn** [comment]
I'm using Emmet expansions as I write my stylesheets today, and it is brilliant. No looking back.
