### ISSUE TITLE
Emmet autocompletion

### ISSUE THREAD

**Issue by ghost** [hudochenkov/Syntax-highlighting-for-PostCSS#8]
Hello,

I've got small problem with Emmet autocompletion.

For example:

```
/* Colors */

$pelorous : #3fbcc0;
$flamingo : #f54b38;
```

Now, when I'm trying to **c -> tab** to get color property, it autocompletes "Colors" from my comment. It does not happen on basic CSS syntax highlighting.

Thanks in advance and thanks for all good work.

**Comment by hudochenkov** [comment]
Are you using the latest Emmet package (v.2016.02.22)? PostCSS support is added to Emmet only this week.

**Comment by ghost** [comment]
Yes.

On Sun, Feb 28, 2016 at 6:15 PM, Aleks Hudochenkov <notifications@github.com

**Comment by hudochenkov** [comment]
Can you show your Sublime Text preferences and Emmet preferences? I haven't this issue on my setup, so I want to check yours settings.

I've trying on this file and everything is working for me:

``` scss
/* Colors */

$pelorous : #3fbcc0;
$flamingo : #f54b38;

a {
    c|
}
```

`|` —is a cursor before I hit Tab.

**Comment by ghost** [comment]
Here's how it looks on my end: http://imgur.com/gbHca3b

I've got default Emmet settings. Nothing changed there.

Here're Sublime settings. Are those you'd like to see?

```
{
    "bold_folder_labels": true,
    "caret_style": "phase",
    "color_scheme": "Packages/Theme - Spacegray/base16-ocean.dark.tmTheme",
    "font_size": 10,
    "highlight_line": true,
    "highlight_modified_tabs": true,
    "ignored_packages":
    [
        "Vintage"
    ],
    "line_padding_bottom": 1,
    "line_padding_top": 1,
    "scroll_past_end": true,
    "shift_tab_unindent": true,
    "tab_size": 4,
    "theme": "Spacegray.sublime-theme",
    "translate_tabs_to_spaces": true,
    "word_wrap": true
}
```

My installed packages:
- Emmet
- BracketHighlighter
- DocBlockr
- ReadmePlease
- SCSS
- Yours ;-)

**Comment by hudochenkov** [comment]
I will look if I can do anything about it. In the meantime you can disable autocomplete for PostCSS. Select `Preferences → Settings — More → Syntax Specific — User` when PostCSS file is open. This will open new file `.../Packages/User/PostCSS.sublime-settings`. Add this to it:

``` json
{
    "auto_complete": false
}
```

**Comment by ghost** [comment]
That did the trick. It's probably workaround but I'm happy with it. Big thanks for help.

**Comment by hudochenkov** [comment]
I've added basic completions, so you can try to enable auto complete. Update `2.1.0` will be available in a hour.
