### ISSUE TITLE
can't work with emmet

### ISSUE THREAD

**Issue by QuietJam** [hudochenkov/Syntax-highlighting-for-PostCSS#9]
Hi,I see your pullrequest to emmet, so i update my emmet the latest version ,but it still not working.when i set syntax to postcss,  input 'db' do not auto complete 'display:block;' , can you give me some advice?
and sorry for my english,hope you can understand what I say!

**Comment by hudochenkov** [comment]
Can you check, please, Emmet version and this package version you've installed? Emmet should be v.2016.02.22 and this package v2.0.0.

**Comment by QuietJam** [comment]
yes,both of them are newest version, finally i found that i need to add an option of postcss scope in emmet setting:
"css_completions_scope": "source.css - meta.selector.css - meta.property-value.css, source.scss - meta.selector.scss - meta.property-value.scss, source.less - meta.selector.css - meta.property-value.css,source.postcss - meta.selector.postcss - meta.property-value.postcss", now it works fine,thanks very much!

**Comment by meduzen** [comment]
Thanks @anrananran, it saves me!
